export type HttpMethod =
  | "GET"
  | "POST"
  | "PATCH"
  | "DELETE"
  | "PUT"
  | "HEAD"
  | "OPTIONS";

export type RmabApiEndpoint = {
  path: string;
  methods: HttpMethod[];
};

export const RMAB_API_ENDPOINTS: RmabApiEndpoint[] = [
  { path: "/api/admin/api-tokens/:id", methods: ["DELETE"] },
  { path: "/api/admin/api-tokens", methods: ["GET", "POST"] },
  { path: "/api/admin/backend-mode", methods: ["GET", "PUT"] },
  { path: "/api/admin/bookdate/toggle", methods: ["PATCH"] },
  { path: "/api/admin/bulk-import/execute", methods: ["POST"] },
  { path: "/api/admin/bulk-import/scan", methods: ["POST"] },
  { path: "/api/admin/downloads/active", methods: ["GET"] },
  { path: "/api/admin/filesystem/browse", methods: ["GET"] },
  { path: "/api/admin/jobs/:id", methods: ["DELETE", "PUT"] },
  { path: "/api/admin/jobs/:id/trigger", methods: ["POST"] },
  { path: "/api/admin/jobs", methods: ["GET", "POST"] },
  { path: "/api/admin/job-status/:id", methods: ["GET"] },
  { path: "/api/admin/logs", methods: ["GET"] },
  { path: "/api/admin/manual-import", methods: ["POST"] },
  { path: "/api/admin/metrics", methods: ["GET"] },
  { path: "/api/admin/notifications/:id", methods: ["DELETE", "GET", "PUT"] },
  { path: "/api/admin/notifications/providers", methods: ["GET"] },
  { path: "/api/admin/notifications", methods: ["GET", "POST"] },
  { path: "/api/admin/notifications/test", methods: ["POST"] },
  { path: "/api/admin/plex/scan", methods: ["POST"] },
  { path: "/api/admin/reported-issues/:id/replace", methods: ["POST"] },
  { path: "/api/admin/reported-issues/:id/resolve", methods: ["POST"] },
  { path: "/api/admin/reported-issues", methods: ["GET"] },
  { path: "/api/admin/requests/:id/approve", methods: ["POST"] },
  { path: "/api/admin/requests/:id/retry-download", methods: ["POST"] },
  { path: "/api/admin/requests/:id", methods: ["DELETE"] },
  { path: "/api/admin/requests/:id/search-terms", methods: ["PATCH"] },
  { path: "/api/admin/requests/pending-approval", methods: ["GET"] },
  { path: "/api/admin/requests/recent", methods: ["GET"] },
  { path: "/api/admin/requests", methods: ["GET"] },
  { path: "/api/admin/settings/audible", methods: ["PUT"] },
  { path: "/api/admin/settings/audiobookshelf/libraries", methods: ["GET"] },
  { path: "/api/admin/settings/audiobookshelf", methods: ["PUT"] },
  { path: "/api/admin/settings/auto-approve", methods: ["GET", "PATCH"] },
  { path: "/api/admin/settings/download-access", methods: ["GET", "PATCH"] },
  { path: "/api/admin/settings/download-client", methods: ["PUT"] },
  { path: "/api/admin/settings/download-clients/categories", methods: ["POST"] },
  { path: "/api/admin/settings/download-clients/:id", methods: ["DELETE", "PUT"] },
  { path: "/api/admin/settings/download-clients", methods: ["GET", "POST"] },
  { path: "/api/admin/settings/download-clients/test", methods: ["POST"] },
  { path: "/api/admin/settings/ebook", methods: ["PUT"] },
  { path: "/api/admin/settings/ebook/test-flaresolverr", methods: ["POST"] },
  { path: "/api/admin/settings/interactive-search", methods: ["GET", "PATCH"] },
  { path: "/api/admin/settings/oidc", methods: ["PUT"] },
  { path: "/api/admin/settings/paths", methods: ["PUT"] },
  { path: "/api/admin/settings/plex/libraries", methods: ["GET"] },
  { path: "/api/admin/settings/plex", methods: ["PUT"] },
  { path: "/api/admin/settings/prowlarr/indexers", methods: ["GET", "PUT"] },
  { path: "/api/admin/settings/prowlarr", methods: ["PUT"] },
  { path: "/api/admin/settings/registration", methods: ["PUT"] },
  { path: "/api/admin/settings", methods: ["GET"] },
  { path: "/api/admin/settings/test-download-client", methods: ["POST"] },
  { path: "/api/admin/settings/test-plex", methods: ["POST"] },
  { path: "/api/admin/settings/test-prowlarr", methods: ["POST"] },
  { path: "/api/admin/users/:id/approve", methods: ["POST"] },
  { path: "/api/admin/users/:id/login-token", methods: ["DELETE", "POST"] },
  { path: "/api/admin/users/:id", methods: ["DELETE", "PUT"] },
  { path: "/api/admin/users/pending", methods: ["GET"] },
  { path: "/api/admin/users", methods: ["GET"] },
  { path: "/api/audible/categories", methods: ["GET"] },
  { path: "/api/audiobooks/:asin/download-status", methods: ["GET"] },
  { path: "/api/audiobooks/:asin/ebook-status", methods: ["GET"] },
  { path: "/api/audiobooks/:asin/fetch-ebook", methods: ["POST"] },
  { path: "/api/audiobooks/:asin/interactive-search-ebook", methods: ["POST"] },
  { path: "/api/audiobooks/:asin/report-issue", methods: ["POST"] },
  { path: "/api/audiobooks/:asin", methods: ["GET"] },
  { path: "/api/audiobooks/:asin/select-ebook", methods: ["POST"] },
  { path: "/api/audiobooks/category/:categoryId", methods: ["GET"] },
  { path: "/api/audiobooks/covers", methods: ["GET"] },
  { path: "/api/audiobooks/new-releases", methods: ["GET"] },
  { path: "/api/audiobooks/popular", methods: ["GET"] },
  { path: "/api/audiobooks/request-with-torrent", methods: ["POST"] },
  { path: "/api/audiobooks/search", methods: ["GET"] },
  { path: "/api/audiobooks/search-torrents", methods: ["POST"] },
  { path: "/api/auth/admin/login", methods: ["POST"] },
  { path: "/api/auth/change-password", methods: ["POST"] },
  { path: "/api/auth/is-local-admin", methods: ["GET"] },
  { path: "/api/auth/local/login", methods: ["POST"] },
  { path: "/api/auth/logout", methods: ["POST"] },
  { path: "/api/auth/me", methods: ["GET"] },
  { path: "/api/auth/oidc/callback", methods: ["GET"] },
  { path: "/api/auth/oidc/login", methods: ["GET"] },
  { path: "/api/authors/:asin/books", methods: ["GET"] },
  { path: "/api/authors/:asin", methods: ["GET"] },
  { path: "/api/authors/search", methods: ["GET"] },
  { path: "/api/auth/plex/callback", methods: ["GET"] },
  { path: "/api/auth/plex/home-users", methods: ["GET"] },
  { path: "/api/auth/plex/login", methods: ["POST"] },
  { path: "/api/auth/plex/switch-profile", methods: ["POST"] },
  { path: "/api/auth/providers", methods: ["GET"] },
  { path: "/api/auth/refresh", methods: ["POST"] },
  { path: "/api/auth/register", methods: ["POST"] },
  { path: "/api/auth/token/login", methods: ["POST"] },
  { path: "/api/bookdate/config", methods: ["DELETE", "GET", "POST"] },
  { path: "/api/bookdate/generate", methods: ["POST"] },
  { path: "/api/bookdate/library", methods: ["GET"] },
  { path: "/api/bookdate/preferences", methods: ["GET", "PUT"] },
  { path: "/api/bookdate/recommendations", methods: ["GET"] },
  { path: "/api/bookdate/swipe", methods: ["POST"] },
  { path: "/api/bookdate/swipes", methods: ["DELETE"] },
  { path: "/api/bookdate/test-connection", methods: ["POST"] },
  { path: "/api/bookdate/undo", methods: ["POST"] },
  { path: "/api/cache/library/:filename", methods: ["GET"] },
  { path: "/api/cache/thumbnails/:filename", methods: ["GET"] },
  { path: "/api/health", methods: ["GET"] },
  { path: "/api/init", methods: ["GET"] },
  { path: "/api/requests/:id/download", methods: ["GET"] },
  { path: "/api/requests/:id/download-token", methods: ["POST"] },
  { path: "/api/requests/:id/fetch-ebook", methods: ["POST"] },
  { path: "/api/requests/:id/interactive-search-ebook", methods: ["POST"] },
  { path: "/api/requests/:id/interactive-search", methods: ["POST"] },
  { path: "/api/requests/:id/manual-search", methods: ["POST"] },
  { path: "/api/requests/:id", methods: ["DELETE", "GET", "PATCH"] },
  { path: "/api/requests/:id/select-ebook", methods: ["POST"] },
  { path: "/api/requests/:id/select-torrent", methods: ["POST"] },
  { path: "/api/requests", methods: ["GET", "POST"] },
  { path: "/api/series/:asin", methods: ["GET"] },
  { path: "/api/series/search", methods: ["GET"] },
  { path: "/api/setup/complete", methods: ["POST"] },
  { path: "/api/setup/download-client-categories", methods: ["POST"] },
  { path: "/api/setup/status", methods: ["GET"] },
  { path: "/api/setup/test-abs", methods: ["POST"] },
  { path: "/api/setup/test-download-client", methods: ["POST"] },
  { path: "/api/setup/test-oidc", methods: ["POST"] },
  { path: "/api/setup/test-paths", methods: ["POST"] },
  { path: "/api/setup/test-plex", methods: ["POST"] },
  { path: "/api/setup/test-prowlarr", methods: ["POST"] },
  { path: "/api/user/api-tokens/:id", methods: ["DELETE"] },
  { path: "/api/user/api-tokens", methods: ["GET", "POST"] },
  { path: "/api/user/goodreads-shelves/:id", methods: ["DELETE", "PATCH"] },
  { path: "/api/user/goodreads-shelves", methods: ["GET", "POST"] },
  { path: "/api/user/hardcover-shelves/:id", methods: ["DELETE", "PATCH"] },
  { path: "/api/user/hardcover-shelves", methods: ["GET", "POST"] },
  { path: "/api/user/home-sections", methods: ["GET", "PUT"] },
  { path: "/api/user/ignored-audiobooks/check/:asin", methods: ["GET"] },
  { path: "/api/user/ignored-audiobooks/:id", methods: ["DELETE"] },
  { path: "/api/user/ignored-audiobooks", methods: ["GET", "POST"] },
  { path: "/api/user/shelves", methods: ["GET"] },
  { path: "/api/user/shelves/sync", methods: ["POST"] },
  { path: "/api/user/watched-authors/:id", methods: ["DELETE"] },
  { path: "/api/user/watched-authors", methods: ["GET", "POST"] },
  { path: "/api/user/watched-series/:id", methods: ["DELETE"] },
  { path: "/api/user/watched-series", methods: ["GET", "POST"] },
  { path: "/api/version", methods: ["GET"] },
];
